name: we_invited
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_analytics: ^6.3.0
  overlay_support: 1.0.5
  flutter_tags: "^0.4.9+1"
  modal_bottom_sheet: 1.0.0+1
  material_dialogs:
  lottie:
  flutter_icons: ^1.1.0
  expandable_text: ^1.2.0
  flutter_multiselect: ^0.5.1
  country_picker: ^1.1.4
  chips_choice: ^2.0.1
  country_list_pick: ^1.0.1+3
  flutter_pdfview: ^1.0.2
  flutter_cupertino_date_picker: ^0.8.0
  url_launcher: ^5.7.10
  flutter_signin_button: ^1.1.0
  frino_icons: ^1.0.1+4
  cached_network_image: ^2.4.1
  rflutter_alert: ^1.1.0
  material_design_icons_flutter: 4.0.5345
  image_cropper: ^1.3.0
  direct_select: "^1.0.3"
  carousel_slider: ^2.2.1
  flutter_svg: ^0.19.1
  material_floating_search_bar: ^0.2.2
  google_fonts: ^1.1.1
  mask_text_input_formatter: ^1.0.7
  dio: ^3.0.10
  image: ^2.1.12
  google_sign_in: ^4.5.9
  image_picker: ^0.6.6+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.4
  provider: 
  flutter_spinkit: ^4.1.2+1
  line_icons: ^0.2.0
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  simple_animations: ^2.2.1
  shared_preferences: ^0.5.10
  firebase_messaging: ^7.0.3
  flutter_screenutil: ^2.3.1
  intl: ^0.16.1
  date_format: ^1.0.8
  path_provider: ^1.6.10
  animated_theme_switcher: ^1.0.5
  line_awesome_flutter: ^1.0.1
  flutter_speed_dial: ^1.2.5
  http: ^0.12.2
  auto_size_text: ^2.1.0
  flushbar: ^1.10.4
  bubble_bottom_bar: ^1.2.0
  uuid: ^2.1.0
  introduction_screen: ^1.0.8
  flutter_local_notifications: ^1.4.4+1
  flip_card: ^0.4.4
  firebase_storage: ^4.0.0
  focused_menu: ^1.0.0
  datetime_picker_formfield: ^1.0.0
  location_permissions: ^3.0.0
  permission_handler: 4.4.0
  geolocator: ^5.1.5
  flutter_easyloading: ^2.0.0
  random_string: ^2.1.0
  flutter_easyrefresh: ^2.1.8




dev_dependencies:
  flutter_test:
    sdk: flutter







# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Wandertucker
      fonts:
        - asset: fonts/Wandertucker.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
